name: Push to CodeCommit on Release

on:
  release:
    types: [published]

jobs:
  push-to-codecommit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install AWS CLI
      run: sudo apt-get install -y awscli

    - name: Configure Git to use AWS CodeCommit credential helper
      run: |
        git config --global credential.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true

    - name: Configure Git user
      run: |
        git config --global user.email "khuleatharva@gmail.com"
        git config --global user.name "Atharva Khule"

    - name: Push to CodeCommit
      run: |
        git remote add codecommit https://git-codecommit.${{ secrets.AWS_REGION }}.amazonaws.com/v1/repos/demo || true
        git push codecommit master
