name: Push to AWS CodeCommit on Release

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with 'v'

jobs:
  push-to-codecommit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Replace with your AWS region

    - name: Push to CodeCommit
      run: |
        git config --global credential.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true
        git remote add codecommit https://git-codecommit.ap-south-1.amazonaws.com/v1/repos/demo
        git push codecommit refs/remotes/origin/main:refs/heads/main
