name: Push to AWS CodeCommit

on:
  push:
    tags:
      - 'v*'  # This triggers the workflow on tag creation (e.g., v1.0.0)

jobs:
  push-to-codecommit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Git
      run: sudo apt-get install -y git

    - name: Push to AWS CodeCommit
      run: |
        git remote add codecommit https://git-codecommit.${{ secrets.AWS_REGION }}.amazonaws.com/v1/repos/demo
        git push codecommit master
