name: Push to CodeCommit on Release

on:
  release:
    types: [published]

jobs:
  push-to-codecommit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # - name: Install AWS CLI
    #   run: sudo apt-get install -y awscli

    - name: Configure Git to use AWS CodeCommit credential helper
      run: |
        git config --global credential.'https://git-codecommit.*.amazonaws.com'.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true

    # - name: Configure Git user
    #   run: |
    #     git config --global user.email "khuleatharva@gmail.com"
    #     git config --global user.name "Atharva Khule"

    - name: Push to CodeCommit
      run: |
        git remote add codecommit https://git-codecommit.ap-south-1.com/v1/repos/demo
        git push codecommit main -f
